services:
  app:
    build:
      dockerfile: Dockerfile
    container_name: app-interview
    restart: unless-stopped
    volumes:
      - .:/var/www/
    env_file: .env
    depends_on:
      - db

  nginx:
    image: nginx:1.19-alpine
    container_name: app-interview-nginx
    restart: on-failure
    ports:
      - "8009:80"
    volumes:
      - .:/var/www/
      - ./nginx:/etc/nginx/conf.d

  db:
    image: mysql:latest
    restart: on-failure
    container_name: app-interview-db
    ports:
      - 3311:3306
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
